### PR TITLE
Fix multiprocessing issues

### PR DESCRIPTION
**Pull request by skudriashev**
@mahmoudimus, please, look at this change, this should solve multiprocessing issues.

### CODE REVIEW

**Comment by skudriashev** [comment]
@mahmoudimus, so, what you think? :)

**Comment by skudriashev** [comment]
@mahmoudimus need to decide whether to commit this or not.

**Comment by mahmoudimus** [comment]
@skudriashev this looks good too, :+1:! let's rebase off master and merge it.

**Comment by mahmoudimus** [comment]
@skudriashev maybe release 0.5 ?

**Comment by skudriashev** [comment]
@mahmoudimus, sure. I'll commit this next days. Thanks!

**Comment by skudriashev** [comment]
Submitted.

**Pull request closed without merging**
